import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar";
import DataProvider from "./_components/DataProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
           <DataProvider>
                    <header >
                <NavBar />  
            </header>
            {children}
            <footer className="absolute bottom-0 left-0 w-full bg-gray-800 text-white py-4">
              <p className="text-center mt-10">© 2023 Your Company. All rights reserved.</p>
              <p className="text-center">Follow us on social media!</p>
            </footer>
           </DataProvider>
       
      </body>
    </html>
  );
}
